=== Clubserg/sew/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria" />
				<xs:element ref="punto_origen" />
				<xs:element ref="tramos" />
				<xs:element ref="resultado_carrera" />
				<xs:element ref="clasificacion_mundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="video" type="xs:string" />

	
	<xs:element name="punto_origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud_punto" />
				<xs:element ref="latitud_punto" />
				<xs:element ref="altitud_punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud_punto">
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-180"/>
				<xs:maxInclusive value="180"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

		<xs:element name="latitud_punto">
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-90"/>
				<xs:maxInclusive value="90"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>



	<xs:element name="altitud_punto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="AltitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="AltitudType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>



	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="punto_origen" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
	<xs:element name="resultado_carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre_piloto" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tiempo" type="xs:duration" />
	<xs:element name="clasificacion_mundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre_piloto" />
				<xs:element ref="puntos" />
				<xs:element ref="posicion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre_piloto" type="xs:string" />
	<xs:element name="puntos" type="xs:integer" />
	<xs:element name="posicion" type="xs:integer" />
</xs:schema>

=== Clubserg/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<uniovi:circuito
    xmlns:uniovi="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <uniovi:nombre>Circuit of the Americas</uniovi:nombre>

    <uniovi:longitud unidad="metros">5513</uniovi:longitud>
    <uniovi:anchura unidad="metros">15</uniovi:anchura>

    <uniovi:fecha>2025-04-13</uniovi:fecha>
    <uniovi:hora>21:00:00</uniovi:hora>
    <uniovi:vueltas>20</uniovi:vueltas>

    <uniovi:localidad>Austin</uniovi:localidad>
    <uniovi:pais>Estados Unidos</uniovi:pais>
    <uniovi:patrocinador>Red Bull</uniovi:patrocinador>

    <uniovi:referencias>
        <uniovi:referencia>https://www.motogp.com/es/event/United+States</uniovi:referencia>
        <uniovi:referencia>https://es.wikipedia.org/wiki/Circuito_de_las_Am%C3%A9ricas</uniovi:referencia>
        <uniovi:referencia>https://www.formula1.com/en/racing/2025/United_States.html</uniovi:referencia>
    </uniovi:referencias>

    <uniovi:galeria>
        <uniovi:fotografia>multimedia/circuitoimg1.jpg</uniovi:fotografia>
        <uniovi:fotografia>multimedia/circuitoimg2.jpg</uniovi:fotografia>
        <uniovi:fotografia>multimedia/circuitoimg3.jpg</uniovi:fotografia>
        <uniovi:video>multimedia/circuitovid1.mp4</uniovi:video>
    </uniovi:galeria>

    <uniovi:punto_origen>
        <uniovi:longitud_punto>-97.6359</uniovi:longitud_punto>
        <uniovi:latitud_punto>30.1328</uniovi:latitud_punto>
        <uniovi:altitud_punto unidad="m">190</uniovi:altitud_punto>
    </uniovi:punto_origen>

    <uniovi:tramos>
        <uniovi:tramo>
            <uniovi:distancia unidad="m">320</uniovi:distancia>
            <uniovi:punto_origen>
                <uniovi:longitud_punto>-97.6361</uniovi:longitud_punto>
                <uniovi:latitud_punto>30.1330</uniovi:latitud_punto>
                <uniovi:altitud_punto unidad="m">190</uniovi:altitud_punto>
            </uniovi:punto_origen>
            <uniovi:sector>1</uniovi:sector>
        </uniovi:tramo>

        <uniovi:tramo>
            <uniovi:distancia unidad="m">450</uniovi:distancia>
            <uniovi:punto_origen>
                <uniovi:longitud_punto>-97.6350</uniovi:longitud_punto>
                <uniovi:latitud_punto>30.1320</uniovi:latitud_punto>
                <uniovi:altitud_punto unidad="m">188</uniovi:altitud_punto>
            </uniovi:punto_origen>
            <uniovi:sector>1</uniovi:sector>
        </uniovi:tramo>

        <uniovi:tramo>
            <uniovi:distancia unidad="m">600</uniovi:distancia>
            <uniovi:punto_origen>
                <uniovi:longitud_punto>-97.6340</uniovi:longitud_punto>
                <uniovi:latitud_punto>30.1310</uniovi:latitud_punto>
                <uniovi:altitud_punto unidad="m">187</uniovi:altitud_punto>
            </uniovi:punto_origen>
            <uniovi:sector>2</uniovi:sector>
        </uniovi:tramo>
    </uniovi:tramos>

    <uniovi:resultado_carrera>
        <uniovi:nombre_piloto>Francesco Bagnaia</uniovi:nombre_piloto>
        <uniovi:tiempo>PT39M0.191S</uniovi:tiempo>
    </uniovi:resultado_carrera>

    <uniovi:clasificacion_mundial>
        <uniovi:piloto>
            <uniovi:nombre_piloto>Marc Márquez</uniovi:nombre_piloto>
            <uniovi:puntos>545</uniovi:puntos>
            <uniovi:posicion>1</uniovi:posicion>
        </uniovi:piloto>
        <uniovi:piloto>
            <uniovi:nombre_piloto>Álex Márquez</uniovi:nombre_piloto>
            <uniovi:puntos>379</uniovi:puntos>
            <uniovi:posicion>2</uniovi:posicion>
        </uniovi:piloto>
        <uniovi:piloto>
            <uniovi:nombre_piloto>Marco Bezzecchi</uniovi:nombre_piloto>
            <uniovi:puntos>282</uniovi:puntos>
            <uniovi:posicion>3</uniovi:posicion>
        </uniovi:piloto>
    </uniovi:clasificacion_mundial>

</uniovi:circuito>
